### PR TITLE
Add slash at the end in permalinks of posts (_config.yml)

### PR DESCRIPTION
**Pull request by ismamz**
Fix my error from another pull request: https://github.com/a11yproject/a11yproject.com/pull/404

### CODE REVIEW

**Comment by davatron5000** [comment]
I assume this changes `/checklist.html` to `/checklist/` as well? Same with `/about.html` to `/about/`? Did you test that? Can you confirm? It's okay if it does, we'll just have to keep that in mind if those pages 404.

**Comment by ismamz** [comment]
Yes, you're right.
The solution is:
- Change `_config.yml` and put `permalink: /posts/:title/`
- Add `permalink: wathever.html` for each page of the site root (only 4 pages)

Then, you can use:
- `/posts/how-to-hide-content/` or `/posts/how-to-hide-content` for posts
- `/checklist.html` or `/checklist/` or `/checklist` for root site pages.

I checked this in another Jekyll project.

Links:
- [Permalinks documentation](https://jekyllrb.com/docs/permalinks/)
- [Front Matter documentation](https://jekyllrb.com/docs/frontmatter/)

**Comment by ismamz** [comment]
@davatron5000 Have you found a solution for this?

**Comment by davatron5000** [comment]
Sorry. I've been busy but hopefully I can just verify it all soon.

**Comment by davatron5000** [comment]
Thanks so much! Sorry it took so long to get merged in.

**Pull request merged**
