### PR TITLE
Added "Basic screen reader commands" link

### PR DESCRIPTION
**Pull request by svinkle**
Excellent article by @LjWatson on basic JAWS, NVDA, and VO commands.

### CODE REVIEW

**Comment by samueljseay** [comment]
+1 This is a nice summary, been looking for something like this

**Comment by davatron5000** [comment]
@svinkle Interested in becoming an admin? You've provided a lot of value and you shouldn't have to PR just for a adding a resource.

**Comment by svinkle** [comment]
@davatron5000 That would be fantastic! Thanks!

**Comment by grayghostvisuals** [comment]
:+1:

**Comment by LjWatson** [comment]
Thanks!

**Pull request merged**
