### PR TITLE
Ft dyslexia fonts

### PR DESCRIPTION
**Pull request by HarcourtHamsa**
Title: A basic intro to dyslexia fonts.

This PR address issue #12

### CODE REVIEW

**Comment by ericwbailey** [comment]
@HarcourtHamsa It looks like this PR is including autoformatted files, much like https://github.com/a11yproject/a11yproject.com/pull/1115. Can you remove them from the PR?

Out of curiosity, what code editor are you using? I might be able to help you out with this issue.

**Comment by HarcourtHamsa** [comment]
Thank you Eric!

You can't believe how relieved I am. I just can't get my hands on what
keeps going wrong. Now that I know, I'll try removing all the autoformatters

  I use VSCode.

**Comment by ericwbailey** [comment]
Okay, I know VS Code! Do you have the Prettier extension, by any chance?

**Comment by HarcourtHamsa** [comment]
Yes Eric , I have the Prettier extension installed

**Comment by ericwbailey** [comment]
Closing in favor of https://github.com/a11yproject/a11yproject.com/pull/1146. I'll continue our conversation there.

**Pull request closed without merging**
