### PR TITLE
Update resources.html

### PR DESCRIPTION
**Pull request by idbygeorge**
Added a link to the Salsa open source syllabus creator developed at Utah State University. GitHub: https://github.com/idbygeorge/salsa. Followed submission guidelines by creating issue #334.

### CODE REVIEW

**Comment by davatron5000** [comment]
Thanks for the commit @idbygeorge! Is this a tool for Web Developers or Educators? I think it's an awesome tool for educators, just a little unsure how applicable it is for general web development. I'm not trying to shut this down or be an overly stern gatekeeper, just curious about the aim/target audience of the Salsa project. It's also quite possible most people who read a11yproject are educators. Would love to hear your thoughts.

**Comment by idbygeorge** [comment]
I think it will be a tool for both. 

Education web developers committed to accessibility will appreciate having a tool that allows instructors to create a critical document by themselves--no accessibility expertise or "fixes" required. Web Developers tasked with fixing inaccessible syllabi will be able to reallocate the many hours spent in processes such as the one shown in this <a href="https://www.youtube.com/watch?v=p9yszeopMZU">57-minute video</a> (details the steps needed to fix a PDF created with MS Word).

Salsa can also be an excellent <strong>development context</strong> for a11y accessibility components/tools/strategies that are ready to demonstrate value in an application that is on track to provide services to 10,000+ students for Fall 2015. For instance: as part of our auditing reports, we will partner with accessibility checkers to provide automated reports for web masters, administrators, accreditors, etc. Just as we are open to working will all Learning Management Systems, we also would like to integrate internally or externally with accessibility checkers that are interested. The same would be true for contrast checkers, open source accessible PDF creators, accessible image tools, etc.

As a pragmatic Instructional Designer, five years ago I chose to focus on the syllabus because it is a "winnable domain". The expectation that syllabi in public higher ed must be accessible to all students can be created HERE and NOW. The Salsa project believes that this will act as a beachhead to move the accessibility conversation forward.

Even though <a href="http://www.lawandtheworkplace.com/2015/06/proposed-web-accessibility-regulations-for-public-accommodations-delayed-yet-again">the government has just kicked the accessibility can down the road again--</a>--by providing an easy-to-use application that educators can use with no cost, I choose to believe that many will step up to their moral obligation to provide accessible documents for all users.

**Comment by idbygeorge** [comment]
Respectfully requesting a reply to my comment posted June 8. Thank you.

**Comment by davatron5000** [comment]
@idbygeorge Sorry I haven't followed up on this. I apologize, that's my fault for not making a quicker decision.

I think Salsa is a great tool but is a fairly niche scope for what the A11Y Project is trying to achieve. We're more on the "accessibility awareness" spectrum as opposed to "specific software recommendations". Thanks so much for contributing and again, sorry.

**Pull request closed without merging**
