### PR TITLE
Color Contrast Article

### PR DESCRIPTION
**Pull request by RachelRVasquez**
This is the complete article from my gist on what color contrast is and
why we need it for web a11y

### CODE REVIEW

**Comment by RachelRVasquez** [comment]
For reference - this is linked to this article issue: https://github.com/a11yproject/a11yproject.com/issues/377#issuecomment-168840502

**Comment by davatron5000** [comment]
LGTM. I think this is ready to go. Does anyone else want to QA this? @joe-watkins @mpiotrowicz? Otherwise I'll pull the trigger in a few minutes.

**Comment by mpiotrowicz** [comment]
good content, I like the color theory background! Would it be appropriate to flesh out more examples of why good color contrast is important? Eg when faced with screen glare, being outside on a sunny day, anyone who's stared at a screen at work all day, etc. (though that might be better content for the impairment article)

**Comment by joe-watkins** [comment]
Great work here.. I love it! Very readable :) To piggyback here I have a couple items:

**Edit:**
"There's a link to W3C's article at the end of this called "The Contrast Minimum" that explains how these ratios are calculated."

I'd love to see a meaningful link presented to the reader at this location rather than directing them to the end of the article.

**Suggestion:**
Also it may be worth pointing out that too much contrast can be an issue as well :) User's with Dyslexia can have trouble with Black on White: http://uxmovement.com/content/6-surprising-bad-practices-that-hurt-dyslexic-users/

**Comment by davatron5000** [comment]
Cool. Let's merge this in and then iterations can be done in another issue and/or via the GitHub Editor.

**Comment by davatron5000** [comment]
:clap: :clap: :clap: It's LIVE! http://a11yproject.com/posts/what-is-color-contrast/

Thanks @RachelRVasquez so much for hopping on board with this project. We all really appreciate the time, work, and new blood you've donated to this project. Look forward to the next one we get to merge in.

**Comment by RachelRVasquez** [comment]
Yay thanks @davatron5000! I'm having a lot of fun and learning from you all as well.

@mpiotrowicz @joe-watkins These sound like great ideas for continuations. :-) I was having trouble deciding how deep to go into the subject so I tried to write it as a "primer" of sorts or an introduction. Then thinking maybe we can write other articles that go into depth of the different contrasts and visual impairments.

I like Joe's idea of editing the Contrast Minimum link so it's in the content versus at the end in "Further Reading". Wondering if maybe we can edit the description of the post so it's less repetitive as well?

**Pull request merged**
