### PR TITLE
Move Netlify toml to root and tweak formatting (#1000)

### PR DESCRIPTION
**Pull request by hidde**
I think this may address issue #1000, it seems the redirects were not taking effect because this file was not in the root of the project.

### CODE REVIEW

**Comment by ericwbailey** [comment]
Oh, thank you for this! I swore the documentation specified placing it in source, and not root.

It also looks like the Netlify checks are failing. I think we need to remove [this line](https://github.com/a11yproject/a11yproject.com/blob/main/.eleventy.js#L77).

**Comment by hidde** [comment]
Oh, just noticed! Trying that out as suggested, seems they still fail. Is the formatting of the redirects file correct?

**Comment by ericwbailey** [comment]
Hm, the plot thickens:

```
3:02:00 PM: Build ready to start
3:02:02 PM: build-image version: ca811f47d4c1cbd1812d1eb6ecb0c977e86d1a1d
3:02:02 PM: build-image tag: v3.3.20
3:02:02 PM: buildbot version: be8ecf2af866e16fa4301cc5c14de2ccbbb21cf4
3:02:03 PM: Fetching cached dependencies
3:02:03 PM: Starting to download cache of 185.0MB
3:02:06 PM: Finished downloading cache in 3.224849917s
3:02:06 PM: Starting to extract cache
3:02:15 PM: Finished extracting cache in 8.945738497s
3:02:15 PM: Finished fetching cache in 12.256648789s
3:02:15 PM: Starting to prepare the repo for build
3:02:15 PM: Preparing Git Reference pull/1010/head
3:02:17 PM: Failing build: Failed to parse configuration
3:02:17 PM: Failed during stage 'Reading and parsing configuration files': When resolving config file /opt/build/repo/netlify.toml:Could not parse configuration fileCannot redefine existing key 'redirects.from'.: exit status 1
3:02:17 PM: Finished processing build request in 15.517199608s
```

**Comment by ericwbailey** [comment]
Looks like we have a winner! Thank you so much for doing this 🎉

**Comment by hidde** [comment]
Yay, awesome! Thanks for helping out, was great to finally work together, even if on a tiny change 👍

**Pull request merged**
