### PR TITLE
Issue #390 - Added new tab pattern

### PR DESCRIPTION
**Pull request by BeyondHyper**

### CODE REVIEW

**Comment by thierryk** [comment]
I think all these examples should include **links** in panels so we can see how _tabbing navigation_ works (as [#390](https://github.com/a11yproject/a11yproject.com/issues/390) does). This is because in most casses, tabbing through/past these panels is very confusing for users.

Back in the day, I created a solution that plugged 2 links at the end of each panel - one to reach the heading of the previous panel (if any) and one to reach the heading of the next panel (if any). This way, keyboard users can navigate **between** panels easily.

**Comment by joe-watkins** [comment]
@thierryk That's a great idea! I forked @BeyondHyper 's pen and added links in the panels and it held up great for keyboard navigation.

@BeyondHyper you mentioned in original issue that your tab pattern was based on @svinkle 's tab pattern .. if it was more than loosely based perhaps we should consider giving credit or point to original Pen from your Pen?

**Comment by BeyondHyper** [comment]
@joe-watkins - I can add the credit in the source code if you think that is better. I already provided credit in the pen description.

**Comment by joe-watkins** [comment]
@BeyondHyper tnx! yes a code comment attribution would do the trick since folks are taken to the edit state over at CodePen. Great contribution!

**Comment by BeyondHyper** [comment]
@joe-watkins thanks and all set! Added it to the js source.

**Comment by BeyondHyper** [comment]
@joe-watkins and @thierryk - I made a couple of changes to the pen. I changed the set up logic so that it doesn't overwrite the tab panel id attribute and implemented @thierryk's idea of having next tab navigation links.

**Comment by thierryk** [comment]
@BeyondHyper 

I think the next tab link is a great improvement for keyboard users but I think you should have:
   * a "next tab" link in the first panel
   * a "previous tab" link **and** a "next tab" link in the second panel
   * a "previous tab" link in the last panel

If you wanted to avoid visual clutter for pointing device users who don't have the need for these links, you could hide them (via `opacity`, off-screen, or else) and reveal them when they get focus (like we often do with skip links).

Makes sense?

**Comment by BeyondHyper** [comment]
@thierryk - that makes sense. Thanks for the feedback!

**Pull request merged**
