### PR TITLE
Added description token to Resources page and updated YAML to match

### PR DESCRIPTION
**Pull request by webuxr**
@davatron5000 Updates to Resources page per #368

### CODE REVIEW

**Comment by webuxr** [comment]
@davatron5000 I checked every. single. link. within the resources.yaml file. Along the way I found some URLs that now redirect, and others that don't exist anymore. Therefore, you'll see some comments that I intend on removing after an initial code review.

Cheers,
_rs

**Comment by davatron5000** [comment]
LGTM so far. Feel free to prune dead links or update with the redirects.

**Comment by davatron5000** [comment]
@webuxr Let me know when you're ready to merge, and if you wouldn't mind tagging all the relevant issues here so we can go through and close those out that'd be sweet.

**Comment by nschonni** [comment]
I've added in #457 to start having the PRs fail for dead links

**Comment by webuxr** [comment]
@davatron5000 So... can #368 be closed and this PR be merged? Or is #457 blocking? 

For reference, I also see #411 and #437 as the only two [other issues labeled as "Resources."](https://github.com/a11yproject/a11yproject.com/issues?q=is%3Aopen+is%3Aissue+label%3AResources), were you wanting me to somehow combine #368, #411, and #437 into a single PR?

Sorry, I don't mean to confuse matters here just be a clear as possible.

Thanks,
_rs

**Comment by nschonni** [comment]
I think #457 should be collaborative, I'm fine with rebasing if needed

**Comment by davatron5000** [comment]
@webuxr I think we're good to merge this. I was waiting on your confirmation.

PLAN:
- Merge this #454, close #368
- #411 is kinda open ended so we should either close it or make the objective more concrete
- #457 will be separate like @nschonni said.
- Then we can either close or knockout other Resources-related issues and PRs
  - https://github.com/a11yproject/a11yproject.com/labels/Resources

**Pull request merged**
