### PR TITLE
Hover and active states

### PR DESCRIPTION
**Pull request by ericwbailey**
This PR addresses https://github.com/a11yproject/a11yproject.com/issues/600. It adds hover and active states for links and buttons.

### CODE REVIEW

**Comment by ericwbailey** [comment]
Here's a screencap of it in action:

Animation demonstrating the hover, active, and focused states for links. Hovered links remove the underline, active has a color change from dark green to umber and restore the underline, and focused states use the browser's native focus ring.

`focus` uses the browser focus ring for now, but I could whip up a background color shift or the like.

**Comment by svinkle** [comment]
Looking good! Is that a custom `:focus` state? Or rather, which browser?

**Comment by ericwbailey** [comment]
Ah, it's Chrome's default focus ring.

**Comment by svinkle** [comment]
Ah I see what's happening; you've set your macOS appearance to "Graphite." 😄

LGTM 👍🚢

**Pull request merged**
