### PR TITLE
Create resources page from a yaml data file

### PR DESCRIPTION
**Pull request by moarsel**
Related to #352 and #361, this PR moves the resources to a YAML file which is pulled into to the resource page and automatically alphabetically ordered.

### CODE REVIEW

**Comment by joe-watkins** [comment]
@moarsel This is cool -- it may be helpful for some contributors to know they can't use tabs in yaml. Perhaps a note about that in the contributing doc or a link to yaml's site? The file format is a bit less common than HTML and could freak out a new contributor :)

**Comment by moarsel** [comment]
That makes sense @joe-watkins I'll see if I can document it a bit more clearly.

**Comment by joe-watkins** [comment]
@moarsel I could see other sections of the site adopting this approach so maybe a general Yaml section in the contributing doc would work?

**Comment by moarsel** [comment]
Ok @joe-watkins I took a first shot at it, let me know what you think.

**Comment by moarsel** [comment]
Hey @joe-watkins, anything else needed to merge this in? If it makes sense, I'm also wondering if I should use this approach with the "patterns" section.

**Comment by joe-watkins** [comment]
@moarsel Lookin' good! Tnx again. I think this same approach could work in Patterns as well... @davatron5000 what ya think?

**Comment by davatron5000** [comment]
❤️ it! Let's merge it in.

**Pull request merged**
