### PR TITLE
Article: Myth: Accessibility is just turning off CSS

### PR DESCRIPTION
**Pull request by ValorNaram**
Referring to issue [#603](https://github.com/a11yproject/a11yproject.com/issues/603). An article about `Myth: Accessibility is just turning off CSS`

### CODE REVIEW

**Comment by ValorNaram** [comment]
_By turning off CSS you forget that blind people are different. Some can distinct between light or dark, others can see structures and the other group of blinds can see a few metres. The structure seeing blinds may use the structure of a page to navigate even more fast. And imaging you turn off CSS for all these different blind people? The result: The structure seeing blinds may get stuck with this new situation._

I think this is a bit too complicated to understand. Any suggestions? I will think over it to find a way to explain it better, but I don't think that I will success

**Comment by smythp** [comment]
Ho is this?

> By turning off CSS,  you are likely to be leaving out many individuals with visual impairments. Remember that blindness and visual impairment is a spectrum. Many, and in fact most, blind or visually impaired individuals have usable vision. By turning off CSS, you remove a tool that might be used by those with low vision or other visual impairments short of total blindness.

I'm low vision myself so this sentiment makes sense to me.

**Comment by ValorNaram** [comment]
Sounds good. The way how I labeled the different groups in the spectrum was the problem.

**Comment by ValorNaram** [comment]
Since I deleted my fork due to inactivity I need to close that PR and fork this repo again, doing the changes and then make a PR again.

**Pull request closed without merging**
