### PR TITLE
Adds checkboxes with localStorage for checklist items

### LINKED ISSUE #942: Add checkboxes to checklist items
Currently the site has no mechanism to let a user check off something in the checklist to mark it as reviewed. 

We should add the ability for someone to check each item on [the Checklist page](https://a11yproject.com/checklist/) off to indicate completion.

- [ ] Incorporate a checkbox pattern
- [ ] Make sure it does not have nested interactive control issues, especially with screen readers/voice control
- [ ] Use localstorage to persist checked/unchecked state between sessions

### PR DESCRIPTION
**Pull request by SaptakS**
Fixes #942 

- Adds checkboxes to each checklist item
- Stores the checklist state in localstorage

### CODE REVIEW

**Comment by SaptakS** [comment]
> The reason for this being that the checkbox cannot be navigated to, or interacted with via keyboard controls—the existing details element overrides it.

Aah. Makes sense.

**Comment by SaptakS** [comment]
So as suggested I have moved the checkbox and out of the details element. It should be navigable with keyboard.
Though I have few things that are bothering me with the design changes that came along with it. To keep the same design as before, I have made the checkbox float right (to appear on right) but via keyboard tab, it will be focused before the details. Secondly, when the summary is in focus, because of the blue color, the checkbox isn't visible. Now since the checkbox appears before the details, there is no way to style it when the summary is focused.

I am not 100% sure what the best way would be or in case you would want some design modifications based on these changes.

**Comment by ericwbailey** [comment]
That's good to know. I'm a little busy until the weekend, but would you like to asynchronously pair on it? I figure I could take a shot at some of the design-related issues.

**Comment by SaptakS** [comment]
> That's good to know. I'm a little busy until the weekend, but would you like to asynchronously pair on it? I figure I could take a shot at some of the design-related issues.

Sure!! Is there a channel somewhere to communicate, or do you prefer GitHub comments?

**Comment by ericwbailey** [comment]
Great! I think GitHub comments would work. I'll tag you either here on in the review code for the parts I shift around.

**Comment by ericwbailey** [comment]
@SaptakS This weekend turned out to be a little busier than expected. Hoping to get something up for you to check out sooner than later.

**Comment by SaptakS** [comment]
@ericwbailey no problem. :)

**Comment by ericwbailey** [comment]
@SaptakS I just pushed up my changes, but I think it was accidentally to [the `checkbox-checklist` branch on this repo](https://github.com/a11yproject/a11yproject.com/tree/checkbox-checklist), and not [yours](https://github.com/SaptakS/a11yproject.com/tree/checkbox-checklist). 

This is admittedly something I don't do that often, so I'll ask a friend for some help getting my changes incorporated into your repo tomorrow.

As for changes, here's the high level notes:

- Created a new `checkboxId` entry for each item in the JSON, as the `for`/`id` pairing was breaking on account of slugify not processing some special entities we use.
- Removed the SVG checkmark in favor of a rotated border, for [more robust support](https://adrianroselli.com/2017/05/under-engineered-custom-radio-buttons-and-checkboxen.html).
- Slight tweaks to the checkbox's accessible name.

**Comment by SaptakS** [comment]
> @SaptakS I just pushed up my changes, but I think it was accidentally to the checkbox-checklist branch on this repo, and not yours.

I can actually fix this. The only thing is there are quite some merge conflicts (in both my commits and yours) with main. So I am trying to rebase properly. I will then try to push if everything looks okay

**Comment by SaptakS** [comment]
@ericwbailey okay. I have rebased on both main and your branch to include all your changes in this PR. So it should be good to go for review.

**Comment by SaptakS** [comment]
>     * Removed the SVG checkmark in favor of a rotated border, for [more robust support](https://adrianroselli.com/2017/05/under-engineered-custom-radio-buttons-and-checkboxen.html).

Also thanks for this link. This is awesome!

**Comment by ericwbailey** [comment]
@SaptakS Absolutely amazing. Thank you so much 🎉

**Pull request merged**
