### PR TITLE
Feature/placeholder label article

### PR DESCRIPTION
**Pull request by RachelRVasquez**
Updated article content and completed template - for issue 170

### CODE REVIEW

**Comment by RachelRVasquez** [comment]
For reference, this article stems from this issue: https://github.com/a11yproject/a11yproject.com/issues/170

**Comment by joe-watkins** [comment]
@RachelRVasquez This is a great post! I'm noticing some weirdness when building with your code fragments. I suggest trying Jekyll's highlighting syntax or indentation.

https://jekyllrb.com/docs/posts/#highlighting-code-snippets

```
{% highlight html %}
... markup here
{% endhighlight %}
```

**Comment by joe-watkins** [comment]
@RachelRVasquez Pushed this one through and I've fixed up the syntax highlight issues :) Thanks for the contribution :)

**Comment by RachelRVasquez** [comment]
@joe-watkins Woops sorry about that - meant to write back to this but never got the chance. Thanks so much for stepping in. :-)

**Pull request merged**
