### PR TITLE
update or remove 404 links

### PR DESCRIPTION
**Pull request by Roshanjossey**
(https://github.com/a11yproject/a11yproject.com/issues/1478)

Remove
 - Accessibility Tester
 - Blindspot: Hidden Biases of Good People
 - Hex Naw
 - Image-Color: Color Contrast Checker
 - Munich Accessibility Meetup
 - Paris Web Accessibility Meetup
 - Stark newsletter

Update
 - Simply Accessible articles to Level Access blog
 - Karl Groves' web accessibility blog link to https://karlgroves.com/category/professional/accessibility/
 - Inclusion: Diversity, The New Workplace & The Will To Change book link to https://jenniferbrownspeaks.com/jbs-book-inclusion
 - Landmarks browser extension link to https://chrome.google.com/webstore/detail/landmark-navigation-via-k/ddpokpbjopmeeiiolheejjpkonlkklgp
 - NoCoffee browser extension link to https://addons.mozilla.org/en-US/firefox/addon/nocoffee/
 - Philly Accessibility Meetup link to https://a11yphl.com/events/
 - I want to see like the colour blind chrome extension to Colorblindly chrome extension

### CODE REVIEW

**Comment by SaptakS** [comment]
Hi. It seems like the Hex Naw link is actually working. Apart from that all looks good.

**Comment by SaptakS** [comment]
There is a merge conflict as well, let me know if you need any help in fixing that.

**Comment by Roshanjossey** [comment]
Thank you for your review @SaptakS, I've resolved conflicts. Could you please review again?

**Review by SaptakS — APPROVED** [review]
Looks good to me.

**Pull request merged**
