### PR TITLE
submitting pattern for a video element  background

### PR DESCRIPTION
**Pull request by mpiotrowicz**
not a super wide use case but could be useful nonetheless

### CODE REVIEW

**Comment by grayghostvisuals** [comment]
Hey there @mpiotrowicz You wanna pull this in? Up to you to close or merge :)

**Comment by mpiotrowicz** [comment]
Hooookay, I've added play/pause functionality as suggested in the above article. I've also added a caveat with a link to the article. I'm torn because overall this isn't always a great pattern for people to use so I don't want to endorse it necessarily, buuut, this is a way of implementing that pattern in a way that's much friendlier. If we get flack from anywhere, I'll happily remove

**Comment by svinkle** [comment]
The icons should be reversed. Currently, while the video plays the 'play' icon is shown when it should be the 'pause' icon. When paused the 'play' icon should be displayed.

**Comment by mpiotrowicz** [comment]
yikes good catch! fixed

**Comment by davatron5000** [comment]
:+1:

**Pull request merged**
