### PR TITLE
Adds flex wrap on v-toc_nav a for proper wrapping

### LINKED ISSUE #1150: Code blocks in ToC
## Summary

On mobile, inline code in the table of contents does weird wrapping.

1. Use Firefox or Chrome on Android mobile,
2. Go to https://www.a11yproject.com/posts/2019-02-15-creating-valid-and-accessible-links/,
3. Scroll down to the _Table of Contents_,
4. Admire.

### Expected result

The text flows like normal text.

### Actual result

Items with a piece of code cause wrapping of all text before the code, then the code (which also wraps), then more wrapping.

Screenshot_20201112-212508

### PR DESCRIPTION
**Pull request by SaptakS**
Fixes #1150 

Also added a bit of margin on both sides of `<code>` in v-toc_nav

### CODE REVIEW

**Comment by ericwbailey** [comment]
@SaptakS Assuming you're working through https://github.com/a11yproject/a11yproject.com/issues/1150#issuecomment-727163297?

Definitely feel free to merge this once you're happy with it 🙂

**Comment by SaptakS** [comment]
@ericwbailey yes I am. :)

**Comment by SaptakS** [comment]
I am aware that safari and IE don't support `gap` yet, hence added the margin rule for them, but this felt like the best solution for most browsers.

**Comment by SaptakS** [comment]
@ericwbailey haven't heard back any further comments on the issue in particular so I am going ahead and merging this. If there are any further issues, we can address in separate PRs. Does that sound good to you?

**Pull request merged**
