### PR TITLE
Add suggested content from #329

### PR DESCRIPTION
**Pull request by elliotekj**
Suggested additions:
- Use SVGs wherever possible
- Provide a “Skip to main content” link
- Ensure no non-decorative content is provided via :before or :after psuedo elements

### CODE REVIEW

**Comment by ElliotEKJ** [comment]
First ever pull request - apologies if I've done something wrong here.

**Comment by svinkle** [comment]
1. I agree with the note on SVG, but I don't see how this is related to web accessibility? Not sure if this should be on the list.

2. Could you add a link to the How-to article? (http://a11yproject.com/posts/skip-nav-links/)

3. Confusing double negative. This could be rewritten as, "Ensure CSS `:before` and `:after` pseudo elements only provide decorative styling, no textual content."

**Comment by joe-watkins** [comment]
@elliotekj Can you fix any merge conflicts and include @svinkle 's recommendations? tnx!

**Comment by joe-watkins** [comment]
Closing in favor of #470

**Pull request closed without merging**
